package com.officepilot.ai.engine.docs

import android.content.Context
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.graphics.pdf.PdfDocument.PageInfo
import com.officepilot.ai.domain.model.DocSection
import com.officepilot.ai.domain.model.DocumentPlan
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.FileOutputStream
import javax.inject.Inject
import javax.inject.Singleton

/**
 * PDF generation engine using Android's native PdfDocument API.
 * Supports multi-page documents with text, tables, charts, and images.
 */
@Singleton
class PdfEngine @Inject constructor(@ApplicationContext private val ctx: Context) {

    companion object {
        const val PAGE_W = 595 // A4 width in points
        const val PAGE_H = 842 // A4 height in points
        const val MARGIN = 50f
        const val CONTENT_W = PAGE_W - 2 * MARGIN.toInt()
        const val LINE_H = 16f
        const val HEADING_SIZE = 18f
        const val BODY_SIZE = 11f
        const val SMALL_SIZE = 9f
        const val TABLE_CELL_PAD = 6f
    }

    private val headingPaint = Paint().apply {
        color = Color.parseColor("#1a237e"); textSize = HEADING_SIZE; typeface = Typeface.DEFAULT_BOLD; isAntiAlias = true
    }
    private val bodyPaint = Paint().apply {
        color = Color.parseColor("#212121"); textSize = BODY_SIZE; isAntiAlias = true
    }
    private val smallPaint = Paint().apply {
        color = Color.parseColor("#757575"); textSize = SMALL_SIZE; isAntiAlias = true
    }
    private val tableBorderPaint = Paint().apply {
        color = Color.parseColor("#bdbdbd"); style = Paint.Style.STROKE; strokeWidth = 0.8f
    }
    private val tableHeaderBg = Paint().apply {
        color = Color.parseColor("#e3f2fd"); style = Paint.Style.FILL
    }
    private val accentPaint = Paint().apply {
        color = Color.parseColor("#1565c0"); style = Paint.Style.FILL
    }

    /** Generate a PDF file from a DocumentPlan. Returns the file path. */
    fun generate(plan: DocumentPlan, images: Map<String, ByteArray> = emptyMap()): String {
        val doc = PdfDocument()
        var pageNum = 1
        var page = doc.startPage(PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
        var canvas = page.canvas
        var y = MARGIN

        // ─── Cover / Title ───
        y += 80f
        val titlePaint = Paint().apply {
            color = Color.parseColor("#0d47a1"); textSize = 26f; typeface = Typeface.DEFAULT_BOLD; isAntiAlias = true
        }
        drawWrappedText(canvas, plan.title, titlePaint, MARGIN, y, CONTENT_W.toFloat()).let { y = it }
        y += 10f
        canvas.drawLine(MARGIN, y, PAGE_W - MARGIN, y, accentPaint.apply { strokeWidth = 2f; style = Paint.Style.STROKE })
        accentPaint.style = Paint.Style.FILL
        y += 30f

        // Date
        val datePaint = Paint(smallPaint).apply { textSize = 10f }
        val dateStr = java.text.SimpleDateFormat("MMMM dd, yyyy", java.util.Locale.getDefault()).format(java.util.Date())
        canvas.drawText("Generated by OfficePilot AI • $dateStr", MARGIN, y, datePaint)
        y += 40f

        // ─── Sections ───
        for (section in plan.sections) {
            // Check if we need a new page
            if (y > PAGE_H - MARGIN - 60) {
                drawPageNumber(canvas, pageNum)
                doc.finishPage(page)
                pageNum++
                page = doc.startPage(PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
                canvas = page.canvas
                y = MARGIN
            }

            when (section.type) {
                "pagebreak" -> {
                    drawPageNumber(canvas, pageNum)
                    doc.finishPage(page)
                    pageNum++
                    page = doc.startPage(PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
                    canvas = page.canvas
                    y = MARGIN
                }
                "text", "bullet_list", "numbered_list" -> {
                    if (section.heading.isNotBlank()) {
                        y += 8f
                        y = drawWrappedText(canvas, section.heading, headingPaint, MARGIN, y, CONTENT_W.toFloat())
                        y += 6f
                    }
                    if (section.content.isNotBlank()) {
                        val lines = if (section.type == "bullet_list") {
                            section.content.split("\n").map { "  •  ${it.trim()}" }
                        } else if (section.type == "numbered_list") {
                            section.content.split("\n").mapIndexed { i, s -> "  ${i + 1}.  ${s.trim()}" }
                        } else null

                        if (lines != null) {
                            for (line in lines) {
                                if (y > PAGE_H - MARGIN - 20) {
                                    drawPageNumber(canvas, pageNum); doc.finishPage(page); pageNum++
                                    page = doc.startPage(PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
                                    canvas = page.canvas; y = MARGIN
                                }
                                y = drawWrappedText(canvas, line, bodyPaint, MARGIN, y, CONTENT_W.toFloat())
                                y += 3f
                            }
                        } else {
                            // Auto page-break for long text
                            val result = drawWrappedTextMultiPage(doc, canvas, page, pageNum,
                                section.content, bodyPaint, MARGIN, y, CONTENT_W.toFloat())
                            canvas = result.canvas; page = result.page; pageNum = result.pageNum; y = result.y
                        }
                        y += 10f
                    }
                }
                "table" -> {
                    if (section.heading.isNotBlank()) {
                        y += 8f; y = drawWrappedText(canvas, section.heading, headingPaint, MARGIN, y, CONTENT_W.toFloat()); y += 6f
                    }
                    val result = drawTable(doc, canvas, page, pageNum, section.tableData, MARGIN, y)
                    canvas = result.canvas; page = result.page; pageNum = result.pageNum; y = result.y
                    y += 15f
                }
                "chart" -> {
                    if (section.heading.isNotBlank()) {
                        y += 8f; y = drawWrappedText(canvas, section.heading, headingPaint, MARGIN, y, CONTENT_W.toFloat()); y += 6f
                    }
                    y = drawBarChart(canvas, section.chartData, MARGIN, y, CONTENT_W.toFloat(), 180f)
                    y += 15f
                }
                "image" -> {
                    val imgKey = section.imageQuery.ifBlank { section.imageUrl }
                    val imgBytes = images[imgKey]
                    if (imgBytes != null) {
                        if (y > PAGE_H - MARGIN - 220) {
                            drawPageNumber(canvas, pageNum); doc.finishPage(page); pageNum++
                            page = doc.startPage(PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
                            canvas = page.canvas; y = MARGIN
                        }
                        if (section.heading.isNotBlank()) {
                            y += 8f; y = drawWrappedText(canvas, section.heading, headingPaint, MARGIN, y, CONTENT_W.toFloat()); y += 6f
                        }
                        y = drawImage(canvas, imgBytes, MARGIN, y, CONTENT_W.toFloat(), 200f)
                        y += 15f
                    }
                }
            }
        }

        drawPageNumber(canvas, pageNum)
        doc.finishPage(page)

        // Save
        val dir = File(ctx.filesDir, "documents").apply { mkdirs() }
        val fileName = "${plan.title.replace(Regex("[^a-zA-Z0-9 ]"), "").replace(" ", "_").take(40)}.pdf"
        val file = File(dir, fileName)
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file.absolutePath
    }

    // ─── Drawing helpers ───

    private fun drawWrappedText(canvas: Canvas, text: String, paint: Paint, x: Float, startY: Float, maxW: Float): Float {
        var y = startY
        val words = text.split(" ")
        var line = ""
        for (word in words) {
            val test = if (line.isEmpty()) word else "$line $word"
            if (paint.measureText(test) > maxW && line.isNotEmpty()) {
                canvas.drawText(line, x, y, paint)
                y += paint.textSize * 1.4f
                line = word
            } else {
                line = test
            }
        }
        if (line.isNotBlank()) {
            canvas.drawText(line, x, y, paint)
            y += paint.textSize * 1.4f
        }
        return y
    }

    private data class PageState(val canvas: Canvas, val page: PdfDocument.Page, val pageNum: Int, val y: Float)

    private fun drawWrappedTextMultiPage(doc: PdfDocument, c: Canvas, p: PdfDocument.Page, pn: Int,
                                         text: String, paint: Paint, x: Float, startY: Float, maxW: Float): PageState {
        var canvas = c; var page = p; var pageNum = pn; var y = startY
        val paragraphs = text.split("\n")
        for (para in paragraphs) {
            val words = para.split(" ")
            var line = ""
            for (word in words) {
                val test = if (line.isEmpty()) word else "$line $word"
                if (paint.measureText(test) > maxW && line.isNotEmpty()) {
                    if (y > PAGE_H - MARGIN - 20) {
                        drawPageNumber(canvas, pageNum); doc.finishPage(page); pageNum++
                        page = doc.startPage(PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
                        canvas = page.canvas; y = MARGIN
                    }
                    canvas.drawText(line, x, y, paint)
                    y += paint.textSize * 1.4f
                    line = word
                } else { line = test }
            }
            if (line.isNotBlank()) {
                if (y > PAGE_H - MARGIN - 20) {
                    drawPageNumber(canvas, pageNum); doc.finishPage(page); pageNum++
                    page = doc.startPage(PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
                    canvas = page.canvas; y = MARGIN
                }
                canvas.drawText(line, x, y, paint)
                y += paint.textSize * 1.4f
            }
            y += 4f
        }
        return PageState(canvas, page, pageNum, y)
    }

    private fun drawTable(doc: PdfDocument, c: Canvas, p: PdfDocument.Page, pn: Int,
                          data: List<List<String>>, x: Float, startY: Float): PageState {
        if (data.isEmpty()) return PageState(c, p, pn, startY)
        var canvas = c; var page = p; var pageNum = pn; var y = startY
        val cols = data.maxOf { it.size }
        val colW = CONTENT_W.toFloat() / cols
        val rowH = 22f

        for ((rowIdx, row) in data.withIndex()) {
            if (y + rowH > PAGE_H - MARGIN) {
                drawPageNumber(canvas, pageNum); doc.finishPage(page); pageNum++
                page = doc.startPage(PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
                canvas = page.canvas; y = MARGIN
            }
            // Header bg
            if (rowIdx == 0) {
                canvas.drawRect(x, y, x + CONTENT_W, y + rowH, tableHeaderBg)
            }
            // Cells
            for ((colIdx, cell) in row.withIndex()) {
                val cx = x + colIdx * colW
                canvas.drawRect(cx, y, cx + colW, y + rowH, tableBorderPaint)
                val paint = if (rowIdx == 0) Paint(bodyPaint).apply { typeface = Typeface.DEFAULT_BOLD } else bodyPaint
                val text = cell.take(30)
                canvas.drawText(text, cx + TABLE_CELL_PAD, y + rowH - TABLE_CELL_PAD, paint)
            }
            y += rowH
        }
        return PageState(canvas, page, pageNum, y)
    }

    private fun drawBarChart(canvas: Canvas, data: Map<String, Double>, x: Float, startY: Float, w: Float, h: Float): Float {
        if (data.isEmpty()) return startY
        val maxVal = data.values.maxOrNull() ?: 1.0
        val barW = (w - 40) / data.size
        val chartBottom = startY + h
        val chartTop = startY + 20

        // Background
        val bgPaint = Paint().apply { color = Color.parseColor("#fafafa"); style = Paint.Style.FILL }
        canvas.drawRect(x, startY, x + w, startY + h, bgPaint)
        canvas.drawRect(x, startY, x + w, startY + h, tableBorderPaint)

        var bx = x + 20
        val colors = intArrayOf(
            Color.parseColor("#1565c0"), Color.parseColor("#2e7d32"),
            Color.parseColor("#e65100"), Color.parseColor("#6a1b9a"),
            Color.parseColor("#c62828"), Color.parseColor("#00838f")
        )
        for ((i, entry) in data.entries.withIndex()) {
            val barH = ((entry.value / maxVal) * (chartBottom - chartTop - 20)).toFloat()
            val barPaint = Paint().apply { color = colors[i % colors.size]; style = Paint.Style.FILL }
            canvas.drawRect(bx, chartBottom - 18 - barH, bx + barW - 5, chartBottom - 18, barPaint)
            // Label
            val labelPaint = Paint(smallPaint).apply { textAlign = Paint.Align.CENTER }
            canvas.drawText(entry.key.take(10), bx + (barW - 5) / 2, chartBottom - 4, labelPaint)
            // Value
            canvas.drawText(formatNumber(entry.value), bx + (barW - 5) / 2, chartBottom - 22 - barH, labelPaint)
            bx += barW
        }
        return startY + h
    }

    private fun drawImage(canvas: Canvas, bytes: ByteArray, x: Float, y: Float, maxW: Float, maxH: Float): Float {
        return try {
            val opts = BitmapFactory.Options().apply { inSampleSize = 2 }
            val bmp = BitmapFactory.decodeByteArray(bytes, 0, bytes.size, opts) ?: return y
            val scale = minOf(maxW / bmp.width, maxH / bmp.height, 1f)
            val dw = bmp.width * scale
            val dh = bmp.height * scale
            val left = x + (maxW - dw) / 2 // Center
            canvas.drawBitmap(bmp, null, RectF(left, y, left + dw, y + dh), null)
            bmp.recycle()
            y + dh + 5f
        } catch (e: Exception) { y }
    }

    private fun drawPageNumber(canvas: Canvas, num: Int) {
        val paint = Paint(smallPaint).apply { textAlign = Paint.Align.CENTER }
        canvas.drawText("— $num —", PAGE_W / 2f, PAGE_H - 25f, paint)
    }

    private fun formatNumber(d: Double): String {
        return if (d >= 1_000_000) String.format("%.1fM", d / 1_000_000)
        else if (d >= 1_000) String.format("%.0fK", d / 1_000)
        else if (d == d.toLong().toDouble()) d.toLong().toString()
        else String.format("%.1f", d)
    }
}
