package com.officepilot.ai.engine.docs

import android.content.Context
import com.officepilot.ai.domain.model.DocSection
import com.officepilot.ai.domain.model.DocumentPlan
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.FileOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream
import javax.inject.Inject
import javax.inject.Singleton

/** Handles CSV, HTML, Markdown, JSON, and ZIP output. */
@Singleton
class TextDocEngine @Inject constructor(@ApplicationContext private val ctx: Context) {

    fun generateCsv(plan: DocumentPlan): String {
        val sb = StringBuilder()
        for (sec in plan.sections) {
            if (sec.type == "table" && sec.tableData.isNotEmpty()) {
                for (row in sec.tableData) {
                    sb.appendLine(row.joinToString(",") { "\"${it.replace("\"", "\"\"")}\"" })
                }
                sb.appendLine()
            }
        }
        if (sb.isBlank()) {
            sb.appendLine("Title,${plan.title}")
            for (sec in plan.sections) {
                if (sec.content.isNotBlank()) sb.appendLine("\"${sec.heading}\",\"${sec.content.take(500)}\"")
            }
        }
        return saveFile(plan.title, "csv", sb.toString())
    }

    fun generateHtml(plan: DocumentPlan, images: Map<String, ByteArray> = emptyMap()): String {
        val sb = StringBuilder()
        sb.appendLine("""<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">""")
        sb.appendLine("""<title>${plan.title}</title><style>
            body{font-family:Segoe UI,system-ui,sans-serif;max-width:900px;margin:0 auto;padding:40px 20px;color:#212121;line-height:1.7}
            h1{color:#0d47a1;border-bottom:3px solid #1565c0;padding-bottom:12px}
            h2{color:#1a237e;margin-top:30px}
            table{width:100%;border-collapse:collapse;margin:20px 0;box-shadow:0 1px 3px rgba(0,0,0,.1)}
            th{background:#1565c0;color:#fff;padding:10px 14px;text-align:left}
            td{padding:8px 14px;border-bottom:1px solid #e0e0e0}
            tr:nth-child(even){background:#f5f5f5}
            .meta{color:#757575;font-size:0.9em;margin-bottom:30px}
            .chart-bar{display:flex;align-items:end;gap:8px;padding:20px;background:#fafafa;border-radius:8px;margin:20px 0}
            .bar{background:linear-gradient(#1565c0,#0d47a1);border-radius:4px 4px 0 0;min-width:40px;text-align:center;color:#fff;font-size:0.8em;padding-top:4px}
            .bar-label{text-align:center;font-size:0.8em;color:#616161;margin-top:4px}
            img{max-width:100%;border-radius:8px;margin:15px 0}
            ul,ol{padding-left:24px}
            li{margin:4px 0}
        </style></head><body>""")
        sb.appendLine("<h1>${plan.title}</h1>")
        val dateStr = java.text.SimpleDateFormat("MMMM dd, yyyy", java.util.Locale.getDefault()).format(java.util.Date())
        sb.appendLine("""<p class="meta">Generated by OfficePilot AI • $dateStr</p>""")

        for (sec in plan.sections) {
            when (sec.type) {
                "text" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("<h2>${sec.heading}</h2>")
                    sec.content.split("\n\n").forEach { sb.appendLine("<p>${it.trim()}</p>") }
                }
                "bullet_list" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("<h2>${sec.heading}</h2>")
                    sb.appendLine("<ul>")
                    sec.content.split("\n").filter { it.isNotBlank() }.forEach { sb.appendLine("<li>${it.trim()}</li>") }
                    sb.appendLine("</ul>")
                }
                "numbered_list" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("<h2>${sec.heading}</h2>")
                    sb.appendLine("<ol>")
                    sec.content.split("\n").filter { it.isNotBlank() }.forEach { sb.appendLine("<li>${it.trim()}</li>") }
                    sb.appendLine("</ol>")
                }
                "table" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("<h2>${sec.heading}</h2>")
                    sb.appendLine("<table>")
                    for ((i, row) in sec.tableData.withIndex()) {
                        sb.append("<tr>")
                        val tag = if (i == 0) "th" else "td"
                        row.forEach { sb.append("<$tag>$it</$tag>") }
                        sb.appendLine("</tr>")
                    }
                    sb.appendLine("</table>")
                }
                "chart" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("<h2>${sec.heading}</h2>")
                    val maxVal = sec.chartData.values.maxOrNull() ?: 1.0
                    sb.appendLine("""<div class="chart-bar" style="height:250px">""")
                    sec.chartData.forEach { (k, v) ->
                        val h = (v / maxVal * 200).toInt()
                        sb.appendLine("""<div style="flex:1;text-align:center"><div class="bar" style="height:${h}px">${formatNum(v)}</div><div class="bar-label">$k</div></div>""")
                    }
                    sb.appendLine("</div>")
                }
                "image" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("<h2>${sec.heading}</h2>")
                    val key = sec.imageQuery.ifBlank { sec.imageUrl }
                    val bytes = images[key]
                    if (bytes != null) {
                        val b64 = android.util.Base64.encodeToString(bytes, android.util.Base64.NO_WRAP)
                        sb.appendLine("""<img src="data:image/jpeg;base64,$b64" alt="${sec.heading}">""")
                    }
                }
                "pagebreak" -> sb.appendLine("""<div style="page-break-after:always"></div>""")
            }
        }
        sb.appendLine("</body></html>")
        return saveFile(plan.title, "html", sb.toString())
    }

    fun generateMarkdown(plan: DocumentPlan): String {
        val sb = StringBuilder()
        sb.appendLine("# ${plan.title}\n")
        for (sec in plan.sections) {
            when (sec.type) {
                "text" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("## ${sec.heading}\n")
                    if (sec.content.isNotBlank()) sb.appendLine("${sec.content}\n")
                }
                "bullet_list" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("## ${sec.heading}\n")
                    sec.content.split("\n").filter { it.isNotBlank() }.forEach { sb.appendLine("- ${it.trim()}") }
                    sb.appendLine()
                }
                "table" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("## ${sec.heading}\n")
                    if (sec.tableData.isNotEmpty()) {
                        sb.appendLine("| ${sec.tableData[0].joinToString(" | ")} |")
                        sb.appendLine("| ${sec.tableData[0].joinToString(" | ") { "---" }} |")
                        sec.tableData.drop(1).forEach { row -> sb.appendLine("| ${row.joinToString(" | ")} |") }
                        sb.appendLine()
                    }
                }
                "chart" -> {
                    if (sec.heading.isNotBlank()) sb.appendLine("## ${sec.heading}\n")
                    sec.chartData.forEach { (k, v) -> sb.appendLine("- **$k**: ${formatNum(v)}") }
                    sb.appendLine()
                }
            }
        }
        return saveFile(plan.title, "md", sb.toString())
    }

    /** Bundle multiple files into a ZIP. */
    fun createZip(filePaths: List<String>, zipName: String): String {
        val dir = File(ctx.filesDir, "documents").apply { mkdirs() }
        val zipFile = File(dir, "$zipName.zip")
        ZipOutputStream(FileOutputStream(zipFile)).use { zos ->
            for (path in filePaths) {
                val file = File(path)
                if (file.exists()) {
                    zos.putNextEntry(ZipEntry(file.name))
                    file.inputStream().use { it.copyTo(zos) }
                    zos.closeEntry()
                }
            }
        }
        return zipFile.absolutePath
    }

    private fun saveFile(title: String, ext: String, content: String): String {
        val dir = File(ctx.filesDir, "documents").apply { mkdirs() }
        val name = "${title.replace(Regex("[^a-zA-Z0-9 ]"), "").replace(" ", "_").take(40)}.$ext"
        val file = File(dir, name)
        file.writeText(content)
        return file.absolutePath
    }

    private fun formatNum(d: Double): String =
        if (d >= 1_000_000) String.format("%.1fM", d / 1_000_000)
        else if (d >= 1_000) String.format("%.0fK", d / 1_000)
        else if (d == d.toLong().toDouble()) d.toLong().toString()
        else String.format("%.1f", d)
}
