package com.officepilot.ai.engine.docs

import android.content.Context
import com.officepilot.ai.domain.model.DocSection
import com.officepilot.ai.domain.model.DocumentPlan
import dagger.hilt.android.qualifiers.ApplicationContext
import org.apache.poi.xwpf.usermodel.*
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTShd
import org.openxmlformats.schemas.wordprocessingml.x2006.main.STShd
import java.io.ByteArrayInputStream
import java.io.File
import java.io.FileOutputStream
import java.math.BigInteger
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Word DOCX generation engine using Apache POI XWPF.
 * Supports headings, tables, images, lists, and professional styling.
 */
@Singleton
class WordEngine @Inject constructor(@ApplicationContext private val ctx: Context) {

    fun generate(plan: DocumentPlan, images: Map<String, ByteArray> = emptyMap()): String {
        val doc = XWPFDocument()

        // ─── Title ───
        val titlePara = doc.createParagraph().apply {
            alignment = ParagraphAlignment.CENTER
            spacingAfter = 200
        }
        titlePara.createRun().apply {
            setText(plan.title)
            isBold = true; fontSize = 24; color = "0D47A1"
            fontFamily = "Calibri"
        }

        // Date line
        val datePara = doc.createParagraph().apply {
            alignment = ParagraphAlignment.CENTER
            spacingAfter = 400
        }
        val dateStr = java.text.SimpleDateFormat("MMMM dd, yyyy", java.util.Locale.getDefault()).format(java.util.Date())
        datePara.createRun().apply {
            setText("Generated by OfficePilot AI • $dateStr")
            fontSize = 10; color = "757575"; isItalic = true
        }

        // Horizontal line
        doc.createParagraph().apply {
            borderBottom = Borders.SINGLE
            spacingAfter = 300
        }

        // ─── Sections ───
        for (section in plan.sections) {
            when (section.type) {
                "text" -> {
                    if (section.heading.isNotBlank()) {
                        addHeading(doc, section.heading)
                    }
                    if (section.content.isNotBlank()) {
                        addParagraph(doc, section.content)
                    }
                }
                "bullet_list" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading)
                    section.content.split("\n").filter { it.isNotBlank() }.forEach { item ->
                        val p = doc.createParagraph().apply {
                            spacingAfter = 60
                            indentationLeft = 400
                        }
                        p.createRun().apply { setText("•  ${item.trim()}"); fontSize = 11 }
                    }
                }
                "numbered_list" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading)
                    section.content.split("\n").filter { it.isNotBlank() }.forEachIndexed { i, item ->
                        val p = doc.createParagraph().apply {
                            spacingAfter = 60
                            indentationLeft = 400
                        }
                        p.createRun().apply { setText("${i + 1}.  ${item.trim()}"); fontSize = 11 }
                    }
                }
                "table" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading)
                    addTable(doc, section.tableData)
                }
                "chart" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading)
                    // Render chart data as a formatted table (POI charts are very complex)
                    val chartTable = mutableListOf<List<String>>()
                    chartTable.add(listOf("Category", "Value"))
                    section.chartData.forEach { (k, v) -> chartTable.add(listOf(k, formatNum(v))) }
                    addTable(doc, chartTable)
                }
                "image" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading)
                    val imgKey = section.imageQuery.ifBlank { section.imageUrl }
                    val imgBytes = images[imgKey]
                    if (imgBytes != null) {
                        addImage(doc, imgBytes)
                    }
                }
                "pagebreak" -> {
                    doc.createParagraph().createRun().addBreak(BreakType.PAGE)
                }
            }
        }

        // Save
        val dir = File(ctx.filesDir, "documents").apply { mkdirs() }
        val fileName = "${plan.title.replace(Regex("[^a-zA-Z0-9 ]"), "").replace(" ", "_").take(40)}.docx"
        val file = File(dir, fileName)
        FileOutputStream(file).use { doc.write(it) }
        doc.close()
        return file.absolutePath
    }

    private fun addHeading(doc: XWPFDocument, text: String) {
        val p = doc.createParagraph().apply {
            style = "Heading2"
            spacingBefore = 200; spacingAfter = 100
        }
        p.createRun().apply {
            setText(text); isBold = true; fontSize = 16; color = "1A237E"
        }
    }

    private fun addParagraph(doc: XWPFDocument, text: String) {
        text.split("\n\n").forEach { para ->
            val p = doc.createParagraph().apply {
                spacingAfter = 120
                alignment = ParagraphAlignment.BOTH
            }
            p.createRun().apply {
                setText(para.trim()); fontSize = 11; fontFamily = "Calibri"
            }
        }
    }

    private fun addTable(doc: XWPFDocument, data: List<List<String>>) {
        if (data.isEmpty()) return
        val cols = data.maxOf { it.size }
        val table = doc.createTable(data.size, cols)
        table.width = 9000

        for ((rowIdx, rowData) in data.withIndex()) {
            val row = table.getRow(rowIdx)
            for ((colIdx, cellVal) in rowData.withIndex()) {
                val cell = row.getCell(colIdx) ?: row.createCell()
                cell.text = cellVal
                if (rowIdx == 0) {
                    // Header styling
                    try {
                        val ctShd = cell.ctTc.addNewTcPr().addNewShd()
                        ctShd.fill = "1565C0"
                        ctShd.color = "FFFFFF"
                        ctShd.`val` = STShd.CLEAR
                        cell.paragraphs.firstOrNull()?.runs?.firstOrNull()?.apply {
                            isBold = true; color = "FFFFFF"; fontSize = 10
                        }
                    } catch (_: Exception) {
                        cell.paragraphs.firstOrNull()?.runs?.firstOrNull()?.isBold = true
                    }
                } else {
                    cell.paragraphs.firstOrNull()?.runs?.firstOrNull()?.fontSize = 10
                }
            }
        }
        doc.createParagraph().spacingAfter = 100
    }

    private fun addImage(doc: XWPFDocument, bytes: ByteArray) {
        try {
            val p = doc.createParagraph().apply { alignment = ParagraphAlignment.CENTER }
            val run = p.createRun()
            val stream = ByteArrayInputStream(bytes)
            run.addPicture(stream, XWPFDocument.PICTURE_TYPE_JPEG, "image.jpg",
                org.apache.poi.util.Units.toEMU(300.0), org.apache.poi.util.Units.toEMU(200.0))
            stream.close()
            doc.createParagraph().spacingAfter = 100
        } catch (e: Exception) {
            // Skip image on failure
        }
    }

    private fun formatNum(d: Double): String =
        if (d == d.toLong().toDouble()) d.toLong().toString()
        else String.format("%.2f", d)
}
