package com.officepilot.ai.engine.docs

import android.content.Context
import com.officepilot.ai.domain.model.DocSection
import com.officepilot.ai.domain.model.DocStyleConfig
import com.officepilot.ai.domain.model.DocumentPlan
import dagger.hilt.android.qualifiers.ApplicationContext
import org.apache.poi.xwpf.usermodel.*
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTShd
import org.openxmlformats.schemas.wordprocessingml.x2006.main.STShd
import java.io.ByteArrayInputStream
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Word DOCX generation engine using Apache POI XWPF.
 * Supports headings, tables, images, quotes, code blocks, lists, and full customisation.
 */
@Singleton
class WordEngine @Inject constructor(@ApplicationContext private val ctx: Context) {

    fun generate(
        plan: DocumentPlan,
        images: Map<String, ByteArray> = emptyMap(),
        style: DocStyleConfig = DocStyleConfig()
    ): String {
        val doc = XWPFDocument()

        // Formatting configs
        val primaryColorHex = style.primaryColorHex.replace("#", "")
        val secondaryColorHex = style.secondaryColorHex.replace("#", "")
        val textColorHex = style.textColorHex.replace("#", "")
        
        val fontName = when (style.fontFamily) {
            "Serif" -> "Georgia"
            "Monospace" -> "Courier New"
            else -> "Calibri"
        }

        // ─── Document Title ───
        val titlePara = doc.createParagraph().apply {
            alignment = ParagraphAlignment.CENTER
            spacingAfter = 180
        }
        titlePara.createRun().apply {
            setText(plan.title)
            isBold = true
            fontSize = 24
            fontFamily = fontName
            color = primaryColorHex
        }

        // Date line
        val datePara = doc.createParagraph().apply {
            alignment = ParagraphAlignment.CENTER
            spacingAfter = 350
        }
        val dateStr = SimpleDateFormat("MMMM dd, yyyy", Locale.getDefault()).format(Date())
        datePara.createRun().apply {
            setText("Generated by OfficePilot AI • $dateStr")
            fontSize = 10
            fontFamily = fontName
            color = "666666"
            isItalic = true
        }

        // Horizontal line
        doc.createParagraph().apply {
            borderBottom = Borders.SINGLE
            spacingAfter = 300
        }

        // ─── Sections ───
        for (section in plan.sections) {
            when (section.type) {
                "text" -> {
                    if (section.heading.isNotBlank()) {
                        addHeading(doc, section.heading, primaryColorHex, fontName)
                    }
                    if (section.content.isNotBlank()) {
                        addParagraph(doc, section.content, textColorHex, fontName, style.lineSpacing)
                    }
                }
                "bullet_list" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading, primaryColorHex, fontName)
                    section.content.split("\n").filter { it.isNotBlank() }.forEach { item ->
                        val p = doc.createParagraph().apply {
                            spacingAfter = 60
                            indentationLeft = 360
                        }
                        p.createRun().apply {
                            setText("•   ${item.trim()}")
                            fontSize = 11
                            fontFamily = fontName
                            color = textColorHex
                        }
                    }
                }
                "numbered_list" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading, primaryColorHex, fontName)
                    section.content.split("\n").filter { it.isNotBlank() }.forEachIndexed { i, item ->
                        val p = doc.createParagraph().apply {
                            spacingAfter = 60
                            indentationLeft = 360
                        }
                        p.createRun().apply {
                            setText("${i + 1}.  ${item.trim()}")
                            fontSize = 11
                            fontFamily = fontName
                            color = textColorHex
                        }
                    }
                }
                "quote" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading, primaryColorHex, fontName)
                    // Styled blockquote
                    val p = doc.createParagraph().apply {
                        spacingBefore = 100
                        spacingAfter = 100
                        indentationLeft = 400
                        indentationRight = 400
                    }
                    p.createRun().apply {
                        setText(section.content.trim())
                        isItalic = true
                        fontSize = 11
                        fontFamily = fontName
                        color = secondaryColorHex
                    }
                }
                "code" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading, primaryColorHex, fontName)
                    // Monospace in shaded cell
                    val codeTable = doc.createTable(1, 1)
                    codeTable.width = 8500
                    val cell = codeTable.getRow(0).getCell(0)
                    cell.paragraphs.firstOrNull()?.apply {
                        spacingBefore = 80
                        spacingAfter = 80
                        indentationLeft = 100
                    }
                    // Apply gray shading
                    try {
                        val ctShd = cell.ctTc.addNewTcPr().addNewShd()
                        ctShd.fill = "F5F5F5"
                        ctShd.`val` = STShd.CLEAR
                    } catch (_: Exception) {}

                    section.content.split("\n").forEachIndexed { index, line ->
                        val p = if (index == 0) cell.paragraphs[0] else cell.addParagraph()
                        p.createRun().apply {
                            setText(line)
                            fontFamily = "Courier New"
                            fontSize = 10
                            color = "333333"
                        }
                    }
                    doc.createParagraph().spacingAfter = 100
                }
                "table" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading, primaryColorHex, fontName)
                    addTable(doc, section.tableData, primaryColorHex, textColorHex, fontName, style.tableStyle)
                }
                "chart" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading, primaryColorHex, fontName)
                    val chartTable = mutableListOf<List<String>>()
                    chartTable.add(listOf("Category", "Value"))
                    section.chartData.forEach { (k, v) -> chartTable.add(listOf(k, formatNum(v))) }
                    addTable(doc, chartTable, primaryColorHex, textColorHex, fontName, style.tableStyle)
                }
                "image" -> {
                    if (section.heading.isNotBlank()) addHeading(doc, section.heading, primaryColorHex, fontName)
                    val imgKey = section.imageQuery.ifBlank { section.imageUrl }
                    val imgBytes = images[imgKey]
                    if (imgBytes != null) {
                        addImage(doc, imgBytes)
                    }
                }
                "pagebreak" -> {
                    doc.createParagraph().createRun().addBreak(BreakType.PAGE)
                }
            }
        }

        // Save
        val dir = File(ctx.filesDir, "documents").apply { mkdirs() }
        val safeTitle = plan.title.replace(Regex("[^a-zA-Z0-9 ]"), "").replace(" ", "_").take(30).ifBlank { "Document" }
        val file = File(dir, "$safeTitle.docx")
        FileOutputStream(file).use { doc.write(it) }
        doc.close()
        return file.absolutePath
    }

    private fun addHeading(doc: XWPFDocument, text: String, colorHex: String, fontFamily: String) {
        val p = doc.createParagraph().apply {
            style = "Heading2"
            spacingBefore = 240
            spacingAfter = 100
            keepNext = true
        }
        p.createRun().apply {
            setText(text)
            isBold = true
            fontSize = 15
            this.fontFamily = fontFamily
            color = colorHex
        }
    }

    private fun addParagraph(
        doc: XWPFDocument, text: String, colorHex: String, fontFamily: String, lineSpacing: Float
    ) {
        text.split("\n\n").forEach { para ->
            val p = doc.createParagraph().apply {
                spacingAfter = 120
                alignment = ParagraphAlignment.BOTH
            }
            p.createRun().apply {
                setText(para.trim())
                fontSize = 11
                this.fontFamily = fontFamily
                color = colorHex
            }
        }
    }

    private fun addTable(
        doc: XWPFDocument, data: List<List<String>>, primaryColorHex: String, textColorHex: String,
        fontFamily: String, tableStyle: String
    ) {
        if (data.isEmpty()) return
        val cols = data.maxOf { it.size }
        val table = doc.createTable(data.size, cols)
        table.width = 9000

        for ((rowIdx, rowData) in data.withIndex()) {
            val row = table.getRow(rowIdx)
            for ((colIdx, cellVal) in rowData.withIndex()) {
                val cell = row.getCell(colIdx) ?: row.createCell()
                cell.text = cellVal
                
                val p = cell.paragraphs.firstOrNull() ?: cell.addParagraph()
                p.spacingBefore = 80
                p.spacingAfter = 80
                p.alignment = ParagraphAlignment.LEFT
                
                val run = p.runs.firstOrNull() ?: p.createRun()
                run.fontFamily = fontFamily
                
                if (rowIdx == 0) {
                    // Header styling
                    try {
                        val ctShd = cell.ctTc.addNewTcPr().addNewShd()
                        ctShd.fill = primaryColorHex
                        ctShd.`val` = STShd.CLEAR
                    } catch (_: Exception) {}
                    run.isBold = true
                    run.color = "FFFFFF"
                    run.fontSize = 10
                } else {
                    // Striped rows or normal style
                    if (tableStyle == "Striped" && rowIdx % 2 == 1) {
                        try {
                            val ctShd = cell.ctTc.addNewTcPr().addNewShd()
                            ctShd.fill = "F7F9FB"
                            ctShd.`val` = STShd.CLEAR
                        } catch (_: Exception) {}
                    }
                    run.color = textColorHex
                    run.fontSize = 10
                }
            }
        }
        doc.createParagraph().spacingAfter = 100
    }

    private fun addImage(doc: XWPFDocument, bytes: ByteArray) {
        try {
            val p = doc.createParagraph().apply { alignment = ParagraphAlignment.CENTER }
            val run = p.createRun()
            val stream = ByteArrayInputStream(bytes)
            run.addPicture(
                stream, XWPFDocument.PICTURE_TYPE_JPEG, "image.jpg",
                org.apache.poi.util.Units.toEMU(340.0), org.apache.poi.util.Units.toEMU(220.0)
            )
            stream.close()
            doc.createParagraph().spacingAfter = 100
        } catch (_: Exception) {}
    }

    private fun formatNum(d: Double): String =
        if (d == d.toLong().toDouble()) d.toLong().toString()
        else String.format("%.2f", d)
}
